engines:
  duplication:
    enabled: true
    config:
      languages:
      - typescript
  tslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*.ts"
exclude_paths: []
